import React, { useState } from 'react';
import { MSDLayoutManifest } from '../../types/msd';
import { soundEngine } from '../../utils/audio';
import { Copy, Check, Download, Code, FileJson, Sparkles } from 'lucide-react';

interface CodeExporterProps {
  manifest: MSDLayoutManifest;
}

export const CodeExporter: React.FC<CodeExporterProps> = ({ manifest }) => {
  const [activeTab, setActiveTab] = useState<'json' | 'react'>('json');
  const [copied, setCopied] = useState(false);

  const jsonString = JSON.stringify(manifest, null, 2);

  // Standalone React component generator
  const reactComponentCode = `import React from 'react';

// MythOS Master Systems Display (MSD) Component
// Generated by MythOS UI Builder (v1.0)
export const ${manifest.layoutId.replace(/[^a-zA-Z0-9]/g, '_')}_MSD = () => {
  const manifest = ${JSON.stringify(manifest, null, 2)};

  return (
    <div className="w-full bg-[#050608] text-slate-100 p-4 rounded-xl border-2 border-[#2f3749] font-sans select-none">
      <header className="flex items-center justify-between p-3 bg-[#37a6d1] text-black font-bold uppercase rounded-t-lg">
        <h1 className="text-lg tracking-widest">{manifest.header.title}</h1>
        <span className="text-xs font-mono">{manifest.header.authorizationCode}</span>
      </header>

      <div className="relative w-full aspect-[16/10] my-4 bg-[#0a0d12] rounded-lg border border-[#2f3749] flex items-center justify-center">
        {/* Render Schematic & Hotspot Nodes */}
        {manifest.msdCanvas.nodes.map((node) => (
          <div
            key={node.id}
            style={{ left: \`\${node.x}%\`, top: \`\${node.y}%\` }}
            className="absolute -translate-x-1/2 -translate-y-1/2 px-2 py-1 bg-[#101216] border border-cyan-400 rounded-full text-xs font-bold text-white shadow-lg cursor-pointer"
          >
            {node.label}
          </div>
        ))}
      </div>

      <footer className="text-xs font-mono text-slate-400 flex justify-between pt-2 border-t border-[#2f3749]">
        <span>SYS-DATE: {manifest.header.stardate}</span>
        <span>THEME: {manifest.theme}</span>
      </footer>
    </div>
  );
};

export default ${manifest.layoutId.replace(/[^a-zA-Z0-9]/g, '_')}_MSD;
`;

  const currentOutput = activeTab === 'json' ? jsonString : reactComponentCode;

  const handleCopy = () => {
    soundEngine.playChime();
    navigator.clipboard.writeText(currentOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    soundEngine.playChime();
    const filename = activeTab === 'json' ? `${manifest.layoutId}.json` : `${manifest.layoutId}.tsx`;
    const mime = activeTab === 'json' ? 'application/json' : 'text/typescript';
    const blob = new Blob([currentOutput], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-2 bg-[#0a0d12] p-3 rounded-lg border border-[#2f3749]">
      <div className="flex items-center justify-between pb-2 border-b border-[#2f3749]">
        <div className="flex items-center gap-2 font-antonio font-bold text-sm text-slate-100 uppercase tracking-wider">
          <Code className="w-4 h-4 text-cyan-400" />
          <span>MANIFEST & COMPONENT EXPORTER</span>
        </div>

        <div className="flex items-center gap-1">
          <button
            type="button"
            onClick={() => setActiveTab('json')}
            className={`px-3 py-1 text-xs font-antonio font-bold uppercase rounded cursor-pointer transition-colors ${
              activeTab === 'json'
                ? 'bg-[#00eeee] text-black'
                : 'bg-[#101216] text-slate-300 hover:text-white'
            }`}
          >
            <FileJson className="w-3.5 h-3.5 inline mr-1" />
            JSON MANIFEST
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('react')}
            className={`px-3 py-1 text-xs font-antonio font-bold uppercase rounded cursor-pointer transition-colors ${
              activeTab === 'react'
                ? 'bg-[#00eeee] text-black'
                : 'bg-[#101216] text-slate-300 hover:text-white'
            }`}
          >
            <Code className="w-3.5 h-3.5 inline mr-1" />
            REACT COMPONENT
          </button>
        </div>
      </div>

      <div className="relative">
        <pre className="w-full max-h-72 overflow-y-auto p-3 bg-[#050608] rounded border border-[#2f3749] text-xs font-mono-data text-cyan-300 leading-relaxed">
          {currentOutput}
        </pre>

        <div className="absolute top-3 right-3 flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1.5 bg-[#1c3c55] border border-[#37a6d1] text-cyan-300 hover:bg-[#2a7193] px-2.5 py-1 rounded text-xs font-antonio font-bold uppercase cursor-pointer transition-colors shadow-lg"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'COPIED!' : 'COPY CODE'}
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-1.5 bg-[#101216] border border-[#2f3749] text-amber-400 hover:bg-[#1c3c55] px-2.5 py-1 rounded text-xs font-antonio font-bold uppercase cursor-pointer transition-colors shadow-lg"
          >
            <Download className="w-3.5 h-3.5" />
            DOWNLOAD
          </button>
        </div>
      </div>
    </div>
  );
};
