import { MSDLayoutManifest } from '../types/msd';

export const DEFAULT_LAYOUT_MANIFEST: MSDLayoutManifest = {
  $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
  layoutId: 'helios-core-msd-01',
  name: 'Quantum Core & System Command Console',
  theme: 'noir-dark',
  header: {
    title: 'MythOS // COMMAND MATRIX WORKSTATION',
    authorizationCode: 'AUTHORIZED // SYNC-CLEARANCE LEVEL A',
    stardate: '103987.42 CY-SEC',
    subTitle: 'PRIMARY QUANTUM CORE & THERMODYNAMIC COHERENCE MONITOR',
  },
  navigation: [
    { id: 'sec-01', label: '01 - SYSTEM MSD', target: 'msd-canvas', active: true },
    { id: 'sec-02', label: '02 - LATTICE FORGE', target: 'lattice-inspector', active: false },
    { id: 'sec-03', label: '03 - ENTROPY SPECTRUM', target: 'entropy-heatmap', active: false },
    { id: 'sec-04', label: '04 - TACTICAL GRID', target: 'tactical-grid', active: false },
  ],
  msdCanvas: {
    schematicAsset: 'quantum_core',
    schematicType: 'quantum_core',
    overlayType: 'thermodynamic',
    nodes: [
      {
        id: 'node-01',
        label: 'COHERENCE FIELD',
        x: 28,
        y: 28,
        metricKey: 'coherenceFactor',
        description: 'Primary quantum confinement field phase matrix',
        status: 'nominal',
      },
      {
        id: 'node-02',
        label: 'ENTROPY DENSITY',
        x: 68,
        y: 35,
        metricKey: 'meanEntropyDensity',
        description: 'Microstate entropy accumulation rate per nanosecond',
        status: 'nominal',
      },
      {
        id: 'node-03',
        label: 'FIELD FLUX',
        x: 48,
        y: 50,
        metricKey: 'warpFieldFlux',
        description: 'Subspace bubble compression ratio and vector harmonics',
        status: 'nominal',
      },
      {
        id: 'node-04',
        label: 'PLASMA INJECTION',
        x: 22,
        y: 72,
        metricKey: 'plasmaFlowRate',
        description: 'Electro-plasma transfer manifold flow pressure',
        status: 'nominal',
      },
      {
        id: 'node-05',
        label: 'SHIELD HARMONICS',
        x: 78,
        y: 70,
        metricKey: 'shieldHarmonics',
        description: 'Multiphasic shield array frequency coherence',
        status: 'nominal',
      },
      {
        id: 'node-06',
        label: 'CORE COOLANT',
        x: 50,
        y: 84,
        metricKey: 'coolantPressure',
        description: 'Cryogenic quantum coolant flow rate & reservoir status',
        status: 'nominal',
      },
    ],
  },
  geometryParams: {
    outerElbowRadius: 32,
    innerElbowRadius: 16,
    padding: 16,
    barGap: 4,
  },
};

export const TEMPLATE_PRESETS: Record<string, MSDLayoutManifest> = {
  quantumCore: DEFAULT_LAYOUT_MANIFEST,
  neuralLattice: {
    ...DEFAULT_LAYOUT_MANIFEST,
    layoutId: 'neural-lattice-forge-02',
    name: 'Neural Lattice Synthesizer',
    theme: 'hyperion-blue',
    header: {
      title: 'MythOS // NEURAL LATTICE FORGE',
      authorizationCode: 'CLEARANCE LEVEL 9',
      stardate: '103988.10 CY-SEC',
      subTitle: 'SYNAPTIC WEAVE & ANTIMATTER MATRIX',
    },
    navigation: [
      { id: 'sec-01', label: '01 - NEURAL WEAVE', target: 'msd-canvas', active: true },
      { id: 'sec-02', label: '02 - COGNITION NODES', target: 'nodes', active: false },
      { id: 'sec-03', label: '03 - ENTROPY METRICS', target: 'metrics', active: false },
    ],
    msdCanvas: {
      schematicAsset: 'neural_lattice',
      schematicType: 'neural_lattice',
      overlayType: 'coherence',
      nodes: [
        { id: 'nl-01', label: 'SYNAPTIC DENSITY', x: 30, y: 30, metricKey: 'coherenceFactor', status: 'nominal' },
        { id: 'nl-02', label: 'SUBSPACE BANDWIDTH', x: 70, y: 30, metricKey: 'subspaceBandwidth', status: 'nominal' },
        { id: 'nl-03', label: 'CORE TEMP', x: 50, y: 65, metricKey: 'coreTemperature', status: 'nominal' },
      ],
    },
  },
  tacticalGrid: {
    ...DEFAULT_LAYOUT_MANIFEST,
    layoutId: 'tactical-hud-03',
    name: 'Defensive Tactical Array',
    theme: 'obsidian-void',
    header: {
      title: 'TACTICAL COMMAND // DEFENSIVE MATRIX',
      authorizationCode: 'ALERT MODE // ARMED',
      stardate: '103988.95 CY-SEC',
      subTitle: 'DEFLECTION HARMONICS & FLUX DENSITY',
    },
    navigation: [
      { id: 'sec-01', label: '01 - DEFENSIVE GRID', target: 'msd-canvas', active: true },
      { id: 'sec-02', label: '02 - EMITTER FLUX', target: 'phasers', active: false },
      { id: 'sec-03', label: '03 - ANOMALY TRACKER', target: 'anomaly', active: false },
    ],
    msdCanvas: {
      schematicAsset: 'bridge_command',
      schematicType: 'bridge_command',
      overlayType: 'shield_harmonics',
      nodes: [
        { id: 'tac-01', label: 'SHIELD FREQUENCY', x: 25, y: 40, metricKey: 'shieldHarmonics', status: 'warning' },
        { id: 'tac-02', label: 'FIELD FLUX', x: 75, y: 40, metricKey: 'warpFieldFlux', status: 'nominal' },
        { id: 'tac-03', label: 'ENTROPY SPIKE', x: 50, y: 75, metricKey: 'meanEntropyDensity', status: 'critical' },
      ],
    },
  },
  monochromeDark: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'monochrome-stealth-01',
    name: 'Noir Monochromatic Operations',
    theme: 'noir-dark',
    layoutArchetype: 'tactical-hud',
    header: {
      title: 'NOIR MONOCHROME // STEALTH TELEMETRY',
      authorizationCode: 'RESTRICTED // SPEC-OPS ARCH',
      stardate: '103989.01 CY-SEC // DEEP SHADOW',
      subTitle: '#000 CANVAS // #111 PANELS // #222 SURFACES // #333 BORDERS // #444 CONTROLS',
    },
    navigation: [
      { id: 'sec-01', label: '01 - NOIR MONITOR', target: 'msd-canvas', active: true },
      { id: 'sec-02', label: '02 - CORE TELEMETRY', target: 'core-telemetry', active: false },
      { id: 'sec-03', label: '03 - FLUX SENSORS', target: 'flux-sensors', active: false },
      { id: 'sec-04', label: '04 - SHADOW LOGS', target: 'logs', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'STEALTH FACTOR', value: '99.98%', unit: 'Ratio', change: '+0.04%', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
      { id: 'kpi-2', label: 'EMISSION DENSITY', value: '0.002 mW', unit: 'Density', change: '-14%', isPositive: true, metricKey: 'meanEntropyDensity', status: 'nominal' },
      { id: 'kpi-3', label: 'POWER EFFICIENCY', value: '94.6%', unit: 'Eff', change: 'Optimal', isPositive: true, metricKey: 'plasmaFlowRate', status: 'nominal' },
      { id: 'kpi-4', label: 'SUB-CORE TEMP', value: '293.1 K', unit: 'Temp', change: 'Stable', isPositive: true, metricKey: 'coreTemperature', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Monochromatic Emission Spectrum', type: 'metric-chart', colSpan: 2, description: 'Zero-glow infrared and electromagnetic signature tracking' },
      { id: 'w-2', title: 'Hardened Subsystem Matrix', type: 'data-table', colSpan: 2, description: 'Isolated stealth nodes and low-power telemetry busses' },
      { id: 'w-3', title: 'Encrypted Black-Box Telemetry Journal', type: 'event-log', colSpan: 1, description: 'Direct cryptographic audit of all local kernel bus events' },
    ],
    msdCanvas: {
      schematicAsset: 'quantum_core',
      schematicType: 'quantum_core',
      overlayType: 'coherence',
      nodes: [
        { id: 'noir-01', label: 'COHERENCE MATRIX', x: 30, y: 32, metricKey: 'coherenceFactor', status: 'nominal' },
        { id: 'noir-02', label: 'ENTROPY FIELD', x: 70, y: 32, metricKey: 'meanEntropyDensity', status: 'nominal' },
        { id: 'noir-03', label: 'THERMAL FLUX', x: 50, y: 68, metricKey: 'coreTemperature', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 4,
      innerElbowRadius: 2,
      padding: 8,
      barGap: 3,
    },
    designRationale: 'Minimalist high-contrast noir black monochrome interface with zero unnecessary color.',
  },
  aegisAmber: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'aegis-amber-telemetry',
    name: 'Aegis Amber Tactical Telemetry',
    theme: 'aegis-amber',
    layoutArchetype: 'aerospace-telemetry',
    header: {
      title: 'AEGIS AMBER // FLIGHT TELEMETRY GRID',
      authorizationCode: 'CLEARANCE: FLIGHT-DECK-01 // TACTICAL AMBER',
      stardate: 'GRID FREQUENCY: 142.8 MHz // SYNCHRONIZED',
      subTitle: 'HIGH-CONTRAST AMBER MONOCHROME & TACTICAL TELEMETRY SENSORS',
    },
    navigation: [
      { id: 'sec-01', label: '01 - AMBER HUD', target: 'hud', active: true },
      { id: 'sec-02', label: '02 - PROPULSION', target: 'propulsion', active: false },
      { id: 'sec-03', label: '03 - SENSOR MATRIX', target: 'sensors', active: false },
      { id: 'sec-04', label: '04 - POWER BUS', target: 'power', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'AMBER BUS VOLTAGE', value: '440.2 V', unit: 'Volts', change: 'Stable', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
      { id: 'kpi-2', label: 'TACTICAL FLUX', value: '88.4 Wb', unit: 'Flux', change: '+2.1 Wb', isPositive: true, metricKey: 'warpFieldFlux', status: 'nominal' },
      { id: 'kpi-3', label: 'THERMAL RADIATOR', value: '298 K', unit: 'Temp', change: 'Optimal', isPositive: true, metricKey: 'coreTemperature', status: 'nominal' },
      { id: 'kpi-4', label: 'PLASMA LEVEL', value: '97.3%', unit: 'Cap', change: 'Nominal', isPositive: true, metricKey: 'plasmaFlowRate', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Tactical Amber Sensor Harmonics', type: 'metric-chart', colSpan: 2, description: 'Continuous spectrum monitoring in the amber wavelength band' },
      { id: 'w-2', title: 'Subsystem Relay Status Vector', type: 'data-table', colSpan: 2, description: 'Real-time telemetry from all active tactical avionics nodes' },
      { id: 'w-3', title: 'Flight Command Transmission Log', type: 'event-log', colSpan: 1, description: 'Encrypted tactical bus telemetry and operator acknowledgments' },
    ],
    msdCanvas: {
      schematicAsset: 'bridge_command',
      schematicType: 'bridge_command',
      overlayType: 'shield_harmonics',
      nodes: [
        { id: 'amber-01', label: 'AMBER BUS', x: 26, y: 36, metricKey: 'plasmaFlowRate', description: 'Primary power bus relay', status: 'nominal' },
        { id: 'amber-02', label: 'RADAR ARRAY', x: 74, y: 36, metricKey: 'warpFieldFlux', description: 'Phased-array tactical telemetry', status: 'nominal' },
        { id: 'amber-03', label: 'TELEMETRY CPU', x: 50, y: 70, metricKey: 'coherenceFactor', description: 'Avionics guidance computer', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 6,
      innerElbowRadius: 3,
      padding: 10,
      barGap: 3,
    },
    designRationale: 'Aegis Amber high-visibility tactical telemetry display with distinct amber HUD aesthetics.',
  },
  voyagerViolet: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'voyager-violet-padd',
    name: 'Voyager Violet PADD Interface',
    theme: 'voyager-violet',
    layoutArchetype: 'modern-dashboard',
    header: {
      title: 'VOYAGER // OPTICAL MATRIX PADD',
      authorizationCode: 'DEEP SPACE EXPLORATION // CLEARANCE BLUE',
      stardate: '104822.15 CY-SEC // SECTOR 001',
      subTitle: 'SUBSPACE SENSORS, ASTROMETRICS & MULTIPHASIC TELEMETRY',
    },
    navigation: [
      { id: 'sec-01', label: '01 - ASTROMETRICS', target: 'astrometrics', active: true },
      { id: 'sec-02', label: '02 - MULTIPHASIC', target: 'multiphasic', active: false },
      { id: 'sec-03', label: '03 - SENSOR SWEEP', target: 'sensors', active: false },
      { id: 'sec-04', label: '04 - SUBSPACE LOG', target: 'logs', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'SUBSPACE COHERENCE', value: '0.999', unit: 'Φ', change: '+0.001', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
      { id: 'kpi-2', label: 'ASTROMETRIC SCAN', value: '98.4 ly', unit: 'Range', change: 'Expanded', isPositive: true, metricKey: 'subspaceBandwidth', status: 'nominal' },
      { id: 'kpi-3', label: 'WARP FLUX HARMONIC', value: '1.02 Wb', unit: 'Flux', change: 'Stable', isPositive: true, metricKey: 'warpFieldFlux', status: 'nominal' },
      { id: 'kpi-4', label: 'CONTAINMENT TEMP', value: '302.4 K', unit: 'Temp', change: 'Nominal', isPositive: true, metricKey: 'coreTemperature', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Astrometric Subspace Frequency Plot', type: 'metric-chart', colSpan: 2, description: 'Long-range optical sensor sweeps and tachyon wave detection' },
      { id: 'w-2', title: 'Multiphasic Shield Cluster Nodes', type: 'data-table', colSpan: 2, description: 'Deflector dish frequency sync and graviton emitters' },
      { id: 'w-3', title: 'Astrometrics Sensor Telemetry Stream', type: 'event-log', colSpan: 1, description: 'Real-time stellar anomalies and spatial distortion alerts' },
    ],
    msdCanvas: {
      schematicAsset: 'quantum_core',
      schematicType: 'quantum_core',
      overlayType: 'coherence',
      nodes: [
        { id: 'vv-01', label: 'ASTROMETRICS', x: 28, y: 34, metricKey: 'subspaceBandwidth', description: 'Primary sensor sweep', status: 'nominal' },
        { id: 'vv-02', label: 'DEFLECTOR ARRAY', x: 72, y: 34, metricKey: 'shieldHarmonics', description: 'Multiphasic shield array', status: 'nominal' },
        { id: 'vv-03', label: 'TACHYON EMITTER', x: 50, y: 72, metricKey: 'coherenceFactor', description: 'Tachyon beam generator', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 8,
      innerElbowRadius: 4,
      padding: 12,
      barGap: 4,
    },
    designRationale: 'Deep space exploratory interface with rich violet tones and high-clarity typography.',
  },
  crtPhosphor: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'crt-phosphor-terminal',
    name: 'Phosphor Green CRT Terminal',
    theme: 'crt-phosphor',
    layoutArchetype: 'tactical-hud',
    header: {
      title: 'RETRO CRT // PHOSPHOR VECTOR TERMINAL',
      authorizationCode: 'UNIX-SYS // VT-100 VECTOR CLEARANCE',
      stardate: 'BAUD: 115200 // MONOCHROME PHOSPHOR',
      subTitle: 'MONOCHROME GREEN VECTOR HUD // TELEMETRY OSCILLOSCOPE',
    },
    navigation: [
      { id: 'sec-01', label: '01 - OSCILLOSCOPE', target: 'scope', active: true },
      { id: 'sec-02', label: '02 - VECTOR NODES', target: 'vectors', active: false },
      { id: 'sec-03', label: '03 - BUFFER TELEMETRY', target: 'buffers', active: false },
      { id: 'sec-04', label: '04 - TTY FEED', target: 'tty', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'PHOSPHOR PERSIST', value: '420 ms', unit: 'Decay', change: 'Fixed', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
      { id: 'kpi-2', label: 'BEAM INTENSITY', value: '18.4 kV', unit: 'Cathode', change: 'Normal', isPositive: true, metricKey: 'plasmaFlowRate', status: 'nominal' },
      { id: 'kpi-3', label: 'SWEEP RATE', value: '60.0 Hz', unit: 'Refresh', change: 'Locked', isPositive: true, metricKey: 'warpFieldFlux', status: 'nominal' },
      { id: 'kpi-4', label: 'TERMINAL NOISE', value: '0.008 dB', unit: 'Noise', change: 'Low', isPositive: true, metricKey: 'meanEntropyDensity', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Cathode Ray Tube Frequency Scan', type: 'metric-chart', colSpan: 2, description: 'Raw analog voltage waveform across sweep coils' },
      { id: 'w-2', title: 'Hardware Register Matrix', type: 'data-table', colSpan: 2, description: 'Direct memory-mapped hardware status indicators' },
      { id: 'w-3', title: 'Serial TTY Telemetry Feed', type: 'event-log', colSpan: 1, description: 'Buffered RS-232 telemetry stream and checksum logs' },
    ],
    msdCanvas: {
      schematicAsset: 'quantum_core',
      schematicType: 'quantum_core',
      overlayType: 'coherence',
      nodes: [
        { id: 'crt-01', label: 'ELECTRON GUN', x: 25, y: 35, metricKey: 'plasmaFlowRate', description: 'Cathode emitter', status: 'nominal' },
        { id: 'crt-02', label: 'DEFLECTION COIL', x: 75, y: 35, metricKey: 'warpFieldFlux', description: 'Magnetic yoke coils', status: 'nominal' },
        { id: 'crt-03', label: 'ANODE CAP', x: 50, y: 70, metricKey: 'coolantPressure', description: 'High-voltage accelerator', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 0,
      innerElbowRadius: 0,
      padding: 8,
      barGap: 2,
    },
    designRationale: 'Monochrome green CRT terminal interface with vintage oscilloscope aesthetics.',
  },
  modernCloudDashboard: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'cloud-telemetry-dashboard',
    name: 'SaaS Cloud Telemetry & Observability Console',
    theme: 'noir-dark',
    layoutArchetype: 'modern-dashboard',
    header: {
      title: 'CLOUD OBSERVER // PRODUCTION MESH',
      authorizationCode: 'ORG-ID: CORP-CLUSTER-09 // US-WEST-1',
      stardate: 'SLA: 99.992% // ALL NODES SYNCHRONIZED',
      subTitle: 'DISTRIBUTED MICROSERVICE INGRESS, LOW-LATENCY IPC, & RUNTIME HEALTH',
    },
    navigation: [
      { id: 'sec-01', label: '01 - METRICS OVERVIEW', target: 'overview', active: true },
      { id: 'sec-02', label: '02 - CLUSTER NODES', target: 'nodes', active: false },
      { id: 'sec-03', label: '03 - DISTRIBUTED TRACES', target: 'traces', active: false },
      { id: 'sec-04', label: '04 - SECURITY AUDIT', target: 'audit', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'TOTAL INGRESS', value: '48.6 GB/s', unit: 'Rate', change: '+12.4%', isPositive: true, metricKey: 'plasmaFlowRate', status: 'nominal' },
      { id: 'kpi-2', label: 'MESH LATENCY P99', value: '1.38 ms', unit: 'Time', change: '-0.32ms', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
      { id: 'kpi-3', label: 'ERROR RATE', value: '0.004%', unit: 'Density', change: '-28.1%', isPositive: true, metricKey: 'meanEntropyDensity', status: 'nominal' },
      { id: 'kpi-4', label: 'CLUSTER THERMAL', value: '318.2 K', unit: 'Temp', change: 'Stable', isPositive: true, metricKey: 'coreTemperature', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Global Ingress Telemetry Vector', type: 'metric-chart', colSpan: 2, description: 'Rolling time-series ingress bandwidth across edge regions' },
      { id: 'w-2', title: 'Kubernetes Pod Fleet Matrix', type: 'data-table', colSpan: 2, description: '24 nodes active, 0 restarts, zero unhandled exceptions' },
      { id: 'w-3', title: 'Real-time Security Event Ledger', type: 'event-log', colSpan: 1, description: 'Continuous cryptographic authorization and ingress verification' },
    ],
    msdCanvas: {
      schematicAsset: 'quantum_core',
      schematicType: 'quantum_core',
      overlayType: 'coherence',
      nodes: [
        { id: 'pod-01', label: 'INGRESS GATEWAY', x: 22, y: 30, metricKey: 'plasmaFlowRate', description: 'Edge proxy and SSL offloader', status: 'nominal' },
        { id: 'pod-02', label: 'TENSOR INFERENCE', x: 74, y: 32, metricKey: 'coherenceFactor', description: 'GPU cluster inference service', status: 'nominal' },
        { id: 'pod-03', label: 'REDIS CACHE MESH', x: 48, y: 55, metricKey: 'subspaceBandwidth', description: 'Distributed memory caching layer', status: 'nominal' },
        { id: 'pod-04', label: 'PERSISTENCE ENGINE', x: 50, y: 78, metricKey: 'coolantPressure', description: 'Multi-AZ database replica pool', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 8,
      innerElbowRadius: 4,
      padding: 12,
      barGap: 4,
    },
    designRationale: 'Extrapolated modern SaaS dashboard with top-tier typography, clean cards, and non-Star-Trek styling.',
  },
  aerospaceMissionControl: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'aerospace-flight-deck',
    name: 'Orbital Aerospace Flight Deck & Telemetry',
    theme: 'aegis-amber',
    layoutArchetype: 'aerospace-telemetry',
    header: {
      title: 'ORBITAL AEROSPACE // FLIGHT OPERATIONS',
      authorizationCode: 'VEHICLE CALLSIGN: ASTRA-07 // ORBITAL DECK',
      stardate: 'MISSION ELAPSED: T+03:42:19 // PHASE 2',
      subTitle: 'ASCENT TRAJECTORY, PROPULSION DYNAMICS, & AVIONICS TELEMETRY',
    },
    navigation: [
      { id: 'sec-01', label: '01 - AVIONICS HUD', target: 'hud', active: true },
      { id: 'sec-02', label: '02 - PROPULSION', target: 'engines', active: false },
      { id: 'sec-03', label: '03 - ORBITAL TRACK', target: 'orbit', active: false },
      { id: 'sec-04', label: '04 - LIFE SUPPORT', target: 'environment', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'ORBITAL VELOCITY', value: '7,794 m/s', unit: 'Speed', change: '+14 m/s', isPositive: true, metricKey: 'warpFieldFlux', status: 'nominal' },
      { id: 'kpi-2', label: 'APOGEE ALTITUDE', value: '412.4 km', unit: 'Alt', change: 'Circular', isPositive: true, metricKey: 'plasmaFlowRate', status: 'nominal' },
      { id: 'kpi-3', label: 'CHAMBER PRESSURE', value: '142.6 bar', unit: 'Press', change: 'Stable', isPositive: true, metricKey: 'coolantPressure', status: 'nominal' },
      { id: 'kpi-4', label: 'HULL INTEGRITY', value: '99.7%', unit: 'Status', change: 'Nominal', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Ascent Trajectory & Delta-V Vector', type: 'metric-chart', colSpan: 2, description: 'Real-time telemetry stream against nominal flight envelope' },
      { id: 'w-2', title: 'Avionics Sensor Health Matrix', type: 'data-table', colSpan: 2, description: 'Triple-redundant IMUs, optical star trackers, and RCS thrusters' },
      { id: 'w-3', title: 'Flight Controller Communication Log', type: 'event-log', colSpan: 1, description: 'Telemetry uplink signals and guidance confirmation packets' },
    ],
    msdCanvas: {
      schematicAsset: 'bridge_command',
      schematicType: 'bridge_command',
      overlayType: 'shield_harmonics',
      nodes: [
        { id: 'aero-01', label: 'MAIN PROPULSION', x: 28, y: 38, metricKey: 'plasmaFlowRate', description: 'Staged combustion rocket engines', status: 'nominal' },
        { id: 'aero-02', label: 'REACTION CONTROL', x: 72, y: 38, metricKey: 'warpFieldFlux', description: 'Cold gas RCS thruster pods', status: 'nominal' },
        { id: 'aero-03', label: 'AVIONICS CORE', x: 50, y: 72, metricKey: 'coherenceFactor', description: 'Primary flight computer array', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 6,
      innerElbowRadius: 3,
      padding: 10,
      barGap: 3,
    },
    designRationale: 'High-contrast flight telemetry interface with technical avionics layout and clean panels.',
  },
  cyberCommandSOC: {
    $schema: 'https://mythos.engine/schemas/ui-builder-v1.json',
    layoutId: 'cyber-soc-matrix',
    name: 'Cyber Defense Security Operations Center (SOC)',
    theme: 'noir-dark',
    layoutArchetype: 'tactical-hud',
    header: {
      title: 'CYBER DEFENSE // THREAT SURVEILLANCE',
      authorizationCode: 'SECTOR: GLOBAL BACKBONE // NOC-04',
      stardate: 'THREAT LEVEL: DEFCON 3 // ZERO BREACHES',
      subTitle: 'DISTRIBUTED IDS/IPS, ANOMALOUS PACKET FLOWS, & CRYPTO SYNC',
    },
    navigation: [
      { id: 'sec-01', label: '01 - THREAT RADAR', target: 'radar', active: true },
      { id: 'sec-02', label: '02 - PACKET FLOW', target: 'packets', active: false },
      { id: 'sec-03', label: '03 - HONEYPOTS', target: 'honeypots', active: false },
      { id: 'sec-04', label: '04 - INCIDENT AUDIT', target: 'incidents', active: false },
    ],
    kpiCards: [
      { id: 'kpi-1', label: 'ACTIVE ATTACK VECTORS', value: '0 CRITICAL', unit: 'Status', change: '-4 Neutralized', isPositive: true, metricKey: 'meanEntropyDensity', status: 'nominal' },
      { id: 'kpi-2', label: 'INGRESS PACKET RATE', value: '38.4 M/s', unit: 'Flow', change: 'Normal', isPositive: true, metricKey: 'subspaceBandwidth', status: 'nominal' },
      { id: 'kpi-3', label: 'CRYPTO KEY VALIDITY', value: '100%', unit: 'Sync', change: 'Quantum Valid', isPositive: true, metricKey: 'shieldHarmonics', status: 'nominal' },
      { id: 'kpi-4', label: 'FIREWALL COHERENCE', value: '99.9%', unit: 'Integrity', change: 'Optimal', isPositive: true, metricKey: 'coherenceFactor', status: 'nominal' },
    ],
    widgets: [
      { id: 'w-1', title: 'Network Packet Anomaly Spectrum', type: 'metric-chart', colSpan: 2, description: 'Volumetric traffic scrutiny with microsecond packet rate profiling' },
      { id: 'w-2', title: 'Segment Isolation & Host Matrix', type: 'data-table', colSpan: 2, description: 'Demilitarized zones, bastion servers, and active VPN tunnels' },
      { id: 'w-3', title: 'Intrusion Detection Alert Stream', type: 'event-log', colSpan: 1, description: 'Automated IP blacklisting, tarpits, and payload inspection entries' },
    ],
    msdCanvas: {
      schematicAsset: 'quantum_core',
      schematicType: 'quantum_core',
      overlayType: 'entropy_density',
      nodes: [
        { id: 'soc-01', label: 'FIREWALL PERIMETER', x: 30, y: 32, metricKey: 'shieldHarmonics', description: 'Next-gen distributed edge firewall', status: 'nominal' },
        { id: 'soc-02', label: 'PACKET INSPECTION', x: 70, y: 32, metricKey: 'meanEntropyDensity', description: 'Deep packet DPI acceleration engine', status: 'nominal' },
        { id: 'soc-03', label: 'CRYPTO VAULT', x: 50, y: 68, metricKey: 'coherenceFactor', description: 'Hardware security module (HSM) cluster', status: 'nominal' },
      ],
    },
    geometryParams: {
      outerElbowRadius: 4,
      innerElbowRadius: 2,
      padding: 8,
      barGap: 3,
    },
    designRationale: 'Tactical HUD layout with sharp technical borders, high contrast, and threat telemetry.',
  },
};

export interface TemplatePresetOption {
  key: string;
  layoutId: string;
  name: string;
  themeId: string;
  archetype?: string;
  category: 'Modern Observability & Telemetry' | 'Tactical & Avionics HUD' | 'Quantum & Subspace Consoles' | 'Custom Extrapolated Templates';
}

export function getUnifiedTemplatePresets(): TemplatePresetOption[] {
  return [
    {
      key: 'modernCloudDashboard',
      layoutId: 'cloud-telemetry-dashboard',
      name: 'SaaS Cloud Observability',
      themeId: 'hyperion-blue',
      archetype: 'modern-dashboard',
      category: 'Modern Observability & Telemetry',
    },
    {
      key: 'aerospaceMissionControl',
      layoutId: 'aerospace-flight-deck',
      name: 'Aerospace Flight Deck',
      themeId: 'aegis-amber',
      archetype: 'aerospace-telemetry',
      category: 'Modern Observability & Telemetry',
    },
    {
      key: 'cyberCommandSOC',
      layoutId: 'cyber-soc-matrix',
      name: 'Cyber Defense SOC',
      themeId: 'noir-dark',
      archetype: 'tactical-hud',
      category: 'Modern Observability & Telemetry',
    },
    {
      key: 'aegisAmber',
      layoutId: 'aegis-amber-telemetry',
      name: 'Aegis Amber',
      themeId: 'aegis-amber',
      archetype: 'aerospace-telemetry',
      category: 'Tactical & Avionics HUD',
    },
    {
      key: 'monochromeDark',
      layoutId: 'monochrome-stealth-01',
      name: 'Noir Monochromatic',
      themeId: 'noir-dark',
      archetype: 'tactical-hud',
      category: 'Tactical & Avionics HUD',
    },
    {
      key: 'tacticalGrid',
      layoutId: 'tactical-hud-03',
      name: 'Defensive Tactical Array',
      themeId: 'obsidian-void',
      archetype: 'lcars-classic',
      category: 'Tactical & Avionics HUD',
    },
    {
      key: 'crtPhosphor',
      layoutId: 'crt-phosphor-terminal',
      name: 'Phosphor Green CRT',
      themeId: 'crt-phosphor',
      archetype: 'tactical-hud',
      category: 'Tactical & Avionics HUD',
    },
    {
      key: 'quantumCore',
      layoutId: 'helios-core-msd-01',
      name: 'Quantum Core Console',
      themeId: 'quantum-cyan',
      archetype: 'lcars-classic',
      category: 'Quantum & Subspace Consoles',
    },
    {
      key: 'neuralLattice',
      layoutId: 'neural-lattice-forge-02',
      name: 'Neural Lattice Synthesizer',
      themeId: 'hyperion-blue',
      archetype: 'lcars-classic',
      category: 'Quantum & Subspace Consoles',
    },
    {
      key: 'voyagerViolet',
      layoutId: 'voyager-violet-padd',
      name: 'Voyager Violet PADD',
      themeId: 'voyager-violet',
      archetype: 'modern-dashboard',
      category: 'Quantum & Subspace Consoles',
    },
  ];
}
